### ISSUE TITLE
Error when closing file that enabled AutoRefresh

### ISSUE THREAD

**Issue by matthew-groth** [Waterflames/AutoRefresh#4]
To reproduce:

1. Open 2 files in sublime and show the console in both
2. enable AutoRefresh in file A
3. close file A
4. in the console of file B, you will see this error at every interval:

```
reloading ~~~/FileA
Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Sublime Text 3/Packages/AutoRefresh-master 2/AutoRefresh.py", line 41, in reloadFile
    row = self.cmd.view.rowcol(self.cmd.view.sel()[0].begin())[0] + 1
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
reloading ~~~/FileA
Traceback (most recent call last):
```

**Comment by Waterflames** [comment]
Fixed in commit 8de1722
